### ISSUE TITLE
ETA on the pending update?

### ISSUE THREAD

**Issue by vikramkakkar** [RobotPajamas/ble113-ota-android#1]
Hi Suresh, this is impressive! Thank you.

I am wondering if you could provide an ETA on the pending update?

I have just begun working with BLE121LR. But, if there's anything I can help with, please let me know.

**Comment by sureshjoshi** [comment]
Hey! I don't have a specific update, actually, I forgot about it until just a few days ago (as in, I left a broken update or something). I'm traveling right now, but when I come back - I'm looking to put more time into this.
