### ISSUE TITLE
Send Multiple Blocks Per Connection

### ISSUE THREAD

**Issue by sw-tt-niravbhavsar** [RobotPajamas/ble113-ota-android#2]
Hello,

Can we send multiple packets per connection to improve transfer rate?

As of now it working fine with sending 1 block per connection.

Help will be appreciated!!!

Thanks.

**Comment by sureshjoshi** [comment]
Hi @sw-tt-niravbhavsar 

It's sending 1 block per connection because it's using acknowledged transfers. Have you tried using unacknowledged transfers? That might go a bit quicker (but on some Android phones, I find issues here if you try to feed data too quickly).
